#!/usr/bin/env bash
# This script is displaying "Best School" 10 times but for the 9th iteration, displays Best School and then Hi

COUNTER=0
while [ $COUNTER -lt 11 ]
do
    if [ $COUNTER = 9 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    let COUNTER+=1
done
